# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _DobleART
else:
    import _DobleART

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _DobleART.delete_SwigPyIterator

    def value(self):
        return _DobleART.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _DobleART.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _DobleART.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _DobleART.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _DobleART.SwigPyIterator_equal(self, x)

    def copy(self):
        return _DobleART.SwigPyIterator_copy(self)

    def next(self):
        return _DobleART.SwigPyIterator_next(self)

    def __next__(self):
        return _DobleART.SwigPyIterator___next__(self)

    def previous(self):
        return _DobleART.SwigPyIterator_previous(self)

    def advance(self, n):
        return _DobleART.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _DobleART.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _DobleART.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _DobleART.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _DobleART.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _DobleART.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _DobleART.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _DobleART:
_DobleART.SwigPyIterator_swigregister(SwigPyIterator)

SHARED_PTR_DISOWN = _DobleART.SHARED_PTR_DISOWN
class DobleART_N(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    nombre = property(_DobleART.DobleART_N_nombre_get, _DobleART.DobleART_N_nombre_set)
    id = property(_DobleART.DobleART_N_id_get, _DobleART.DobleART_N_id_set)
    src = property(_DobleART.DobleART_N_src_get, _DobleART.DobleART_N_src_set)
    precio = property(_DobleART.DobleART_N_precio_get, _DobleART.DobleART_N_precio_set)
    categoria = property(_DobleART.DobleART_N_categoria_get, _DobleART.DobleART_N_categoria_set)
    siguiente = property(_DobleART.DobleART_N_siguiente_get, _DobleART.DobleART_N_siguiente_set)
    anterior = property(_DobleART.DobleART_N_anterior_get, _DobleART.DobleART_N_anterior_set)

    def __init__(self, id, categoria, nombre, precio, src):
        _DobleART.DobleART_N_swiginit(self, _DobleART.new_DobleART_N(id, categoria, nombre, precio, src))
    __swig_destroy__ = _DobleART.delete_DobleART_N

# Register DobleART_N in _DobleART:
_DobleART.DobleART_N_swigregister(DobleART_N)

class DobleLART(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cabeza = property(_DobleART.DobleLART_cabeza_get, _DobleART.DobleLART_cabeza_set)
    final = property(_DobleART.DobleLART_final_get, _DobleART.DobleLART_final_set)
    ArticuloSeleccionado = property(_DobleART.DobleLART_ArticuloSeleccionado_get, _DobleART.DobleLART_ArticuloSeleccionado_set)
    articuloesta = property(_DobleART.DobleLART_articuloesta_get, _DobleART.DobleLART_articuloesta_set)

    def __init__(self):
        _DobleART.DobleLART_swiginit(self, _DobleART.new_DobleLART())

    def add(self, id, categoria, nombre, precio, src):
        return _DobleART.DobleLART_add(self, id, categoria, nombre, precio, src)

    def Display(self):
        return _DobleART.DobleLART_Display(self)

    def BuscarArticulo(self, id):
        return _DobleART.DobleLART_BuscarArticulo(self, id)

    def deseleccionarArticulo(self):
        return _DobleART.DobleLART_deseleccionarArticulo(self)

    def precioArticuloSeleccionado(self):
        return _DobleART.DobleLART_precioArticuloSeleccionado(self)

    def IDArticuloSeleccionado(self):
        return _DobleART.DobleLART_IDArticuloSeleccionado(self)

    def nombreArticuloSeleccionado(self):
        return _DobleART.DobleLART_nombreArticuloSeleccionado(self)

    def srcArticuloSeleccionado(self):
        return _DobleART.DobleLART_srcArticuloSeleccionado(self)

    def categoriaArticuloSeleccionado(self):
        return _DobleART.DobleLART_categoriaArticuloSeleccionado(self)

    def mover(self, inicio, final):
        return _DobleART.DobleLART_mover(self, inicio, final)

    def Bubble(self):
        return _DobleART.DobleLART_Bubble(self)
    __swig_destroy__ = _DobleART.delete_DobleLART

# Register DobleLART in _DobleART:
_DobleART.DobleLART_swigregister(DobleLART)



