# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _cola
else:
    import _cola

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _cola.delete_SwigPyIterator

    def value(self):
        return _cola.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _cola.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _cola.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _cola.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _cola.SwigPyIterator_equal(self, x)

    def copy(self):
        return _cola.SwigPyIterator_copy(self)

    def next(self):
        return _cola.SwigPyIterator_next(self)

    def __next__(self):
        return _cola.SwigPyIterator___next__(self)

    def previous(self):
        return _cola.SwigPyIterator_previous(self)

    def advance(self, n):
        return _cola.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _cola.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _cola.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _cola.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _cola.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _cola.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _cola.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _cola:
_cola.SwigPyIterator_swigregister(SwigPyIterator)

SHARED_PTR_DISOWN = _cola.SHARED_PTR_DISOWN
class NodoCola(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_cola.NodoCola_x_get, _cola.NodoCola_x_set)
    y = property(_cola.NodoCola_y_get, _cola.NodoCola_y_set)
    siguiente = property(_cola.NodoCola_siguiente_get, _cola.NodoCola_siguiente_set)

    def __init__(self, x, y):
        _cola.NodoCola_swiginit(self, _cola.new_NodoCola(x, y))
    __swig_destroy__ = _cola.delete_NodoCola

# Register NodoCola in _cola:
_cola.NodoCola_swigregister(NodoCola)

class Cola(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    m = property(_cola.Cola_m_get, _cola.Cola_m_set)
    alto = property(_cola.Cola_alto_get, _cola.Cola_alto_set)
    siguiente = property(_cola.Cola_siguiente_get, _cola.Cola_siguiente_set)
    cabeza = property(_cola.Cola_cabeza_get, _cola.Cola_cabeza_set)
    Xcola = property(_cola.Cola_Xcola_get, _cola.Cola_Xcola_set)
    Ycola = property(_cola.Cola_Ycola_get, _cola.Cola_Ycola_set)

    def __init__(self):
        _cola.Cola_swiginit(self, _cola.new_Cola())

    def agregardim(self, m):
        return _cola.Cola_agregardim(self, m)

    def enque(self, x, y):
        return _cola.Cola_enque(self, x, y)

    def dequeue(self):
        return _cola.Cola_dequeue(self)

    def obtenerXcola(self):
        return _cola.Cola_obtenerXcola(self)

    def obtenerYcola(self):
        return _cola.Cola_obtenerYcola(self)

    def peek(self):
        return _cola.Cola_peek(self)

    def GraphoCola(self):
        return _cola.Cola_GraphoCola(self)
    __swig_destroy__ = _cola.delete_Cola

# Register Cola in _cola:
_cola.Cola_swigregister(Cola)



